# Generated by Django 2.0 on 2018-07-13 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SubjectsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_name', models.CharField(max_length=500, null=True, verbose_name='Problem name')),
                ('text', models.TextField()),
                ('template', models.CharField(max_length=500, null=True, verbose_name='Problem Template')),
                ('number_of_numeral', models.PositiveIntegerField(default=1, null=True)),
                ('topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SubjectsApp.Topic', verbose_name='Topic ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemNumeral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeral_name', models.CharField(max_length=500, null=True, verbose_name='Numeral name')),
                ('numeral_number', models.PositiveIntegerField(default=0, null=True)),
                ('question', models.TextField()),
                ('number_of_steps', models.PositiveIntegerField(default=1, null=True)),
                ('problem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProblemsApp.Problem', verbose_name='Problem ID')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=500, null=True, verbose_name='Step name')),
                ('step_number', models.PositiveIntegerField(default=0, null=True)),
                ('explanation', models.TextField()),
                ('video', models.CharField(max_length=500, null=True)),
                ('instruction', models.TextField()),
                ('number_of_substeps', models.PositiveIntegerField(default=0, null=True)),
                ('problem_num_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProblemsApp.ProblemNumeral', verbose_name='Problem Num ID')),
            ],
        ),
        migrations.CreateModel(
            name='Substep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substep_name', models.CharField(max_length=500, null=True, verbose_name='Substep name')),
                ('substep_number', models.PositiveIntegerField(default=0, null=True)),
                ('answer', models.TextField(null=True)),
                ('hint', models.TextField(null=True)),
                ('step_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProblemsApp.Step', verbose_name='Step ID')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='substep',
            unique_together={('step_id', 'substep_number')},
        ),
        migrations.AlterUniqueTogether(
            name='step',
            unique_together={('problem_num_id', 'step_number')},
        ),
        migrations.AlterUniqueTogether(
            name='problemnumeral',
            unique_together={('problem_id', 'numeral_number')},
        ),
        migrations.AlterUniqueTogether(
            name='problem',
            unique_together={('topic_id', 'problem_name')},
        ),
    ]
