# Generated by Django 2.0 on 2018-07-18 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SubjectsApp', '0002_auto_20180718_0314'),
        ('ProblemsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='date_prob_creation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='problem_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='problem',
            name='number_of_numeral',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_name',
            field=models.CharField(blank=True, default=1, max_length=500, verbose_name='Problem name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='problem',
            name='template',
            field=models.CharField(default={}, max_length=500, verbose_name='Problem Template'),
        ),
        migrations.AlterField(
            model_name='problemnumeral',
            name='number_of_steps',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='problemnumeral',
            name='numeral_name',
            field=models.CharField(blank=True, default='a', max_length=500, verbose_name='Numeral name'),
        ),
        migrations.AlterField(
            model_name='problemnumeral',
            name='numeral_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='step',
            name='number_of_substeps',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='step',
            name='problem_num_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProblemsApp.ProblemNumeral', verbose_name='Problem Numeral ID'),
        ),
        migrations.AlterField(
            model_name='step',
            name='step_name',
            field=models.CharField(blank=True, default=1, max_length=500, verbose_name='Step name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='step',
            name='step_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='substep',
            name='answer',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='substep',
            name='hint',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='substep',
            name='substep_name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Substep name'),
        ),
        migrations.AlterField(
            model_name='substep',
            name='substep_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RemoveField(
            model_name='problem',
            name='id',
        ),
        migrations.AlterUniqueTogether(
            name='problem',
            unique_together={('topic_id', 'problem_id')},
        ),
    ]
