# Generated by Django 2.0 on 2018-07-31 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProblemsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='date_prob_creation',
            field=models.DateField(blank=True, default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='problem',
            name='problem_status',
            field=models.BooleanField(default='False'),
        ),
    ]
