# Generated by Django 2.0 on 2018-07-18 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubjectsApp', '0002_auto_20180718_0314'),
        ('ProblemsApp', '0002_auto_20180718_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='problem',
            name='problem_id',
        ),
        migrations.AlterUniqueTogether(
            name='problem',
            unique_together={('topic_id', 'id')},
        ),
    ]
