# Generated by Django 2.0 on 2018-07-18 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProblemsApp', '0005_problem_date_prob_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='date_prob_creation',
            field=models.DateField(blank=True, default='0000-00-00'),
        ),
    ]
