# Generated by Django 2.0 on 2018-07-18 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProblemsApp', '0006_auto_20180718_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='date_prob_creation',
            field=models.DateField(blank=True, default='2000-01-01'),
        ),
    ]
