# Generated by Django 2.0 on 2018-07-18 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProblemsApp', '0007_auto_20180718_0319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='date_prob_creation',
        ),
    ]
