# Generated by Django 2.0 on 2018-07-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='number_solved_problems',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentproblem',
            name='answer_file',
            field=models.CharField(blank=True, default=1, max_length=100, verbose_name='answer_file'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentproblem',
            name='fail_attemps',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='studentproblem',
            name='succesful_attemps',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='studentstep',
            name='fail_attemps',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='studentstep',
            name='number_of_substeps',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='studentstep',
            name='succesful_attemps',
            field=models.IntegerField(default='0'),
        ),
    ]
