# Generated by Django 2.0 on 2018-07-31 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LocationApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True, verbose_name='First name')),
                ('last_name', models.CharField(max_length=100, null=True, verbose_name='Last name')),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=100, null=True, verbose_name='Book title')),
                ('publication_date', models.DateField(blank=True)),
                ('authors', models.ManyToManyField(to='BooksApp.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.PositiveIntegerField(default='0', null=True)),
                ('chapter_name', models.CharField(max_length=100, null=True, verbose_name='Chapter name')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BooksApp.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True, verbose_name='Address')),
                ('website', models.URLField(blank=True)),
                ('city', models.ManyToManyField(to='LocationApp.City')),
                ('country', models.ManyToManyField(to='LocationApp.Country')),
                ('state_province', models.ManyToManyField(to='LocationApp.State')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BooksApp.Publisher'),
        ),
    ]
