# Generated by Django 2.0 on 2018-07-13 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LocationApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('college_id', models.SlugField(primary_key=True, serialize=False, verbose_name='College code')),
                ('college_name', models.CharField(max_length=500, null=True, verbose_name='College')),
                ('college_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LocationApp.City')),
                ('college_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LocationApp.Country')),
                ('college_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LocationApp.State')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.SlugField(primary_key=True, serialize=False, verbose_name='School code')),
                ('school_name', models.CharField(max_length=500, null=True, verbose_name='School')),
                ('school_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LocationApp.City')),
                ('school_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LocationApp.Country')),
                ('school_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LocationApp.State')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('university_id', models.SlugField(primary_key=True, serialize=False, verbose_name='University code')),
                ('university_name', models.CharField(max_length=500, null=True, verbose_name='University')),
                ('university_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LocationApp.City')),
                ('university_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LocationApp.Country')),
                ('university_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LocationApp.State')),
            ],
        ),
    ]
