# Generated by Django 2.0 on 2018-07-31 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProblemsApp', '0002_auto_20180731_2332'),
        ('LocationApp', '0001_initial'),
        ('SchoolsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=100)),
                ('number_input_problems', models.IntegerField(default='0')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LocationApp.Country', verbose_name='Country name')),
                ('school', models.ManyToManyField(to='SchoolsApp.School')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProblems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProblemsApp.Problem', verbose_name='Problem ID')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeachersApp.Teacher', verbose_name='Teacher ID')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='teacherproblems',
            unique_together={('teacher_id', 'problem_id')},
        ),
    ]
